# Använd en officiell Python 3.9-bild
FROM python:3.9-slim

# Sätt arbetskatalogen i containern
WORKDIR /app

# Kopiera alla filer från den aktuella mappen till containern
COPY . .

# Installera alla beroenden från requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Kör os_data.py som standard när containern startar
CMD ["python", "src/os_data.py"]
